### ISSUE TITLE
Performer Sign-in

### ISSUE THREAD

**Issue by thoonk78** [UWOSWETeam7/TheaterApp#1]
**User Story**
As a performer, I want to be able to sign in by entering an access code, then selecting my name on the website

**Acceptance Criteria**
- UI sign-in page created
- Business to validate access code before entry
- Business logic has tests to validate sign-in

**Tasks**

- [ ] Make UI
- [ ] Make Business Logic
- [ ] Make or use existing access code generator
- [ ] Connect UI to business logic
- [ ] Create User database
- [ ] Create XUnit tests to validate sign-in
