### ISSUE TITLE
Stage Manager and Choreographer sign-in alert

### ISSUE THREAD

**Issue by thoonk78** [UWOSWETeam7/TheaterApp#2]
**User Story**
As a stage manager or choreographer I want to be alerted that a performer has signed in

**Acceptance Criteria**
- Email sent when song roster is complete
- Database updated to show performer is checked in
- Tests to make sure alert comes up when supposed to

**Tasks**

- [ ] Business Logic to send email when roster is checked in
- [ ] Database call to get list checked in / not checked in people
- [ ] Test to see if alert is sent when sign-in happens
