### ISSUE TITLE
Performer rehearsal location alert

### ISSUE THREAD

**Issue by thoonk78** [UWOSWETeam7/TheaterApp#3]
**User Story**
As a performer, I want to be alerted where to go for rehearsal

**Acceptance Criteria**
- Alert sent by email
- User Homepage shows rehearsal location and time
- Tests written

**Tasks**
- [ ] Business logic to send email alert
- [ ] Database update of rehearsal location and time
- [ ] User Database updated to include email
- [ ] Test email alert
- [ ] Test Database update
