### ISSUE TITLE
Performer Add song

### ISSUE THREAD

**Issue by thoonk78** [UWOSWETeam7/TheaterApp#6]
**User Story**
As a performer I want to be able to add songs I’m performing in, and then see which songs I am in.

**Acceptance criteria**
Sign in should be easy to use for all ages. It should then alert the stage manager that the performer is at the rehearsal. Then it should tell the performer which building or which room in the building they need to go for their specific song rehearsal.

**Tasks**

- [ ] Create UI to get user input for song info
- [ ] BL to call database
- [ ] Validation of data
- [ ] Tests to make sure proper function
