### ISSUE TITLE
Stage Manager send miss alert

### ISSUE THREAD

**Issue by thoonk78** [UWOSWETeam7/TheaterApp#8]
**User story**
As a stage manager, I want to be able to alert performers with a warning that only one rehearsal of a song can be missed. Inadition, alert performers when two rehearsals of the song are missed then they are pulled from that song.

**Acceptance criteria**
Alert should be clear as to number of missed rehearsals and if pulled from song or not. Stage manager  will be notified of a flagged performer that missed a rehearsal of a song. Then the stage manager issues an alert based on the severity of missing attendance.

**Tasks** 

- [ ] UI for alert page
- [ ] BL to send alert
- [ ] Tests to make sure alert gets to user
- [ ] Tests to make sure they properly get pulled from song
